---
# roles/launch/tasks/main.yml
- name: Launch the new EC2 Instance
  local_action:
    module: ec2
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    instance_profile_name: "{{ IamProfile }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    count: "{{ count }}"
    instance_tags:
      Name: webserver 
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

- name: refresh inventory
  local_action:
    module: shell
    args: /root/cake/cake/inventory/ec2.py --refresh-cache

- name: Refresh in-memory EC2 cache
  local_action:
    module: meta
    args: refresh_inventory
